### PR TITLE
Pull Request for Archived Apple Homepage Clone, Microverse Project on Background and Gradients

### PR DESCRIPTION
**Pull request by temesghentekeste**
Kindly request a pull request for the first solo project of the MIcroverse Technical Curriculum.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @temesghentekeste, great job with the first attempt 👍 Let us improve our code by working on the comments below:
- Let us replace each of the `````` under ```<div class="showcase">``` with ```<div>```, give it a class and set the background-image for them. Since our main focus for this project is using backgrounds and gradients
- Let us increase the width of the main content so it looks like the original
- Let us center our ```<nav>``` so it aligns in the center
- Let us fix the 1 warning returned by the w3validator
- Let us apply the DRY rule so we avoid repeating code as we currently have. Let us work a little with the CSS  file

[OPTIONAL]
We can improve semantics by replacing ```<div class="showcase">``` with ```<main>```


Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack 😄

**Comment by temesghentekeste** [comment]
Thank you, @addod19  for your feedback and I will fix code as per your suggestions.

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes :red_circle:
### Hey :wave: 
## You're almost there :muscle: :+1: 

# I think something broke in your code somewhere, you're missing the main image

Requested Page:
Screenshot from 2020-04-11 22-46-36
Yours:
Screenshot from 2020-04-11 22-43-33

## before submiting again, please check your code in [GitHack](https://raw.githack.com/)
## Right now your code is showing only [THIS](https://rawcdn.githack.com/temesghentekeste/archived-apple-clone/30c32a2c6707770cf479afd3c2ae9177ed153153/index.html) in [GitHack](https://raw.githack.com/) and in my computer
## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by temesghentekeste** [comment]
Thanks, @Dandush03 kindly inform you I fixed the errors.

**Comment by sumancrest0001** [comment]
**Status: Changes required**

Hello @temesghentekeste
  Nice try :clap: 
There are still issues with layout of the page.
[Required] Navbar and the texts above the main sections are not aligned properly. Let's try to fix this problem. I checked on chrome as well as firefox.
Screenshot from 2020-04-13 00-14-39

Let me know if you have different on your computer. 
Slack handle **Suman Shrestha**

Kindly make the change and submit for another review.
:+1: :+1:

**Comment by temesghentekeste** [comment]
Thanks, but the page looks fine in my local pc; I think the problem is the page is not responsive as it stands.

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @temesghentekeste 👋

You've come quite far on this. Great job making a few of the requested changes by the previous reviews.👍👌

However, there are just some adjustments left, you are almost there. You've got this💪

Kindly make the following changes:

-  [ ]  Required - Ensure you validate your HTML code with this [validator tool](https://validator.w3.org/nu/#file) and fix the error described.

- [ ] Required - Kindly remove inline comments on your CSS file if you need to refer to a previous version of your code, please use git history.

- [ ] Optional - Also as stated in the previous review your project would look even more awesome if you use semantic HTML. Consider changing this: `<div class="container grid">` to this: `<main class="container grid">`.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by temesghentekeste** [comment]
Thanks, kindly inform you I have fixed every issue.

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  @temesghentekeste 👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

However, kindly remove the single comment that exists on your HTML file. Fix this before you merge this branch.

Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Comment by temesghentekeste** [comment]
Thanks, @mikenath223 and I will fix the comment before I merge it.

**Pull request merged**
